Algoritmo "Senha"
// Disciplina   : [Linguagem e Lógica de Programação] 
// Professor   : Antonio Carlos Nicolodi 
Var
// Seção de Declarações das variáveis 
senhaPadrao, senha: inteiro

Inicio

senhaPadrao <- 2312
escreval("Digite a senha: ")
leia(senha)
enquanto senhaPadrao <> senha faca
   escreval("Numero invalido!")
   escreval("tente novamente: ")
   leia(senha)
fimenquanto
escreval("acesso permitido: ")
Fimalgoritmo